### ISSUE TITLE
Replace verbose examples with new library methods

### ISSUE THREAD

**Issue by lognaturel** [getodk/pyodk#35]
App User Provisioner is especially ripe for improving. There might be other improvements possible.

**Comment by ayushanand18** [comment]
The App User Provisioner example (here: https://github.com/getodk/pyodk/blob/master/examples/app_user_provisioner.py) looks good to start with. I understand from the code that, we have a list of users from a csv file and we need to provision the non-existing users on the server.

From a design perspective this function could look like:
```python
def provision_users(client: Client, file: str, settings: dict, project_meta: dict, save_path: str) -> None:
    """
    :param client: An instance of the Client class or simply returned by Client().open().
    :param file: The path of the csv file to read users list from.
    :param settings: The Collection settings as a dictionary.
    :param project_meta: The dictionary of project metadata with id, name, list of forms to access, app user role id, etc.
    :param save_path: The path to folder to save all images generated and the pdf file.
    """
```

Thoughts?

**Comment by lindsay-stevens** [comment]
@ayushanand18 thanks for contributing to pyODK! The example shows how a user of pyODK could implement a script to provision app users. The script was written before PR #32, which added `client.projects.create_app_users()` to simplify the process.

I suggest approaching it as if re-implementing the script using current features of pyODK. As a docs resource, the simpler it is, the easier it will be for users to follow and adapt it to other things.

**Comment by ayushanand18** [comment]
Thanks for the clarification @lindsay-stevens. I get the correct interpretation of this issue now, as "We need to refactor the example script per the recent changes in the package modules." 

Do we have a docs for this package?

**Comment by lognaturel** [comment]
You can find docs strings inline. You can build https://github.com/getodk/pyodk/pull/31 locally with `mkdocs start` go see a rendered version if you find that helpful.

**Comment by ayushanand18** [comment]
> You can find docs strings inline. You can build #31 locally with `mkdocs start` go see a rendered version if you find that helpful.

Noted. Thanks!
