### ISSUE TITLE
Support entities

### ISSUE THREAD

**Issue by lognaturel** [getodk/pyodk#62]
- [x] decide whether we're using "dataset" or "entity list". The former is what the API calls a collection of entities, the latter is what's user-facing. `pyodk` is kind of in the middle. I'm leaning towards "entity list" because it matches form design and it's often the same person who design forms and does analysis. I think we should [align with ruODK](https://github.com/ropensci/ruODK/pull/153/files#r1522000629). 
    - Using `entity_list`

- [ ] `list` https://docs.getodk.org/central-api-entity-management/#entities-metadata
- [ ] `create` https://docs.getodk.org/central-api-entity-management/#creating-an-entity; I think it should take a required entity list name, required label, required dict for data, and an optional uuid (function can generate a uuid4 if none provided)
- [ ] `get_table` https://docs.getodk.org/central-api-odata-endpoints/#id3 same as https://getodk.github.io/pyodk/submissions/#pyodk._endpoints.submissions.SubmissionService.get_table

Should we also create an `entity_list` module by analogy to the `form`/`submission` separation?
- [ ] `list` https://docs.getodk.org/central-api-dataset-management/#datasets
- [ ] `create` upcoming (https://github.com/getodk/central/issues/575)
- [ ] `add_property` upcoming (https://github.com/getodk/central/issues/576)

**Comment by kanhirun** [comment]
I just want to echo that this feature is something my team is interested as well. We are exploring `pyodk` to help continuously pull data from ODK Cloud from submissions data. However, **pulling entity data is greatly preferred** as we end up using submissions data to come up with our own "entity model".

**Comment by lognaturel** [comment]
Thanks so much for that feedback, @kanhirun! Our approach to `pyodk` has been to add support for functionality as its requested so please let us know as you have needs that we could address!

In general, you should be able to use any Central endpoint directly using https://getodk.github.io/pyodk/http-methods/. It's not as convenient as using the built-in methods but it's something to consider if we don't yet have nice methods for functionality you'd like to use.
